Initial version of urdf_utilities
ros-controls/urdf_geometry_parser pull request #1
Opened 2017-05-02 15:17 UTC by vincentrou

If we agree on this, I can add test.

2017-05-02 18:34 UTC, tfoote commented
I'd strongly recommend reviewing the name and picking a specific scope. You can always have multiple packages. http://wiki.ros.org/ROS/Patterns/Conventions

2017-05-03 10:18 UTC, bmagyar commented
Thanks Tully,  I guess we were a bit too quick with that choice.

On May 2, 2017 7:34 PM, "Tully Foote" <notifications@github.com> wrote:

> I'd strongly recommend reviewing the name and picking a specific scope.
> You can always have multiple packages. http://wiki.ros.org/ROS/
> Patterns/Conventions
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ros-controls/urdf_utilities/pull/1#issuecomment-298722349>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADXH4dy0r4BkIURYhMn7UVEpZ7d0_WRlks5r13dMgaJpZM4NOSSJ>
> .
>

2017-05-03 14:37 UTC, vincentrou commented
What about those names : `urdf_kinematics_extractor`,  `urdf_kinematics_reader` or `urdf_kinematics` ?

2017-05-03 14:42 UTC, ipa-mdl commented
`urdf_kinematics_utils`? or `_helpers`?

2017-05-03 15:31 UTC, bmagyar commented
Stepping back to the original name:
* vehicle_kinematics_utilities
* vehicle_kinematics_helpers


On May 3, 2017 3:42 PM, "Mathias Lüdtke" <notifications@github.com> wrote:

> urdf_kinematics_utils? or _helpers?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ros-controls/urdf_utilities/pull/1#issuecomment-298931623>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADXH4QVnlt3xHXHG_mfqCrz71Jvo2L2tks5r2JJagaJpZM4NOSSJ>
> .
>

2017-05-03 15:39 UTC, ipa-mdl commented
> Stepping back to the original name: [...] vehicle [...]

Acutally, most of the code is not related to vehicles..
I could imagine to add other URDF/kinematic functions for use with other controllers as well.

2017-05-04 09:41 UTC, bmagyar commented
Thank you @ipa-mdl , you are right. Having that in mind keeps the door open to such functions in the future too.

* `ros_control_urdf_tools`
* `controller_urdf_tools`
* `controllers_urdf_tools`
* `urdf_controller_tools`
* `controller_urdf_helpers`
* `controller_urdf_utilities`

2017-05-04 09:42 UTC, bmagyar commented
@graiola @efernandez feel free to chime in too ;)

2017-05-04 15:21 UTC, efernandez requested changes
Minor changes... but I'd basically add `roslint`

2017-05-04 15:21 UTC, efernandez commented on CMakeLists.txt
> + src/${PROJECT_NAME}.cpp
indentation

2017-05-04 15:21 UTC, efernandez commented on include/urdf_utilities/urdf_utilities.h
> +#ifndef URDF_UTILITIES_H
License ?

2017-05-04 15:21 UTC, efernandez commented on include/urdf_utilities/urdf_utilities.h
> +#define URDF_UTILITIES_H
roslint: `URDF_UTILITIES_URDF_UTILITIES_H`

I'd encourage to add a roslint test

2017-05-04 15:21 UTC, efernandez commented on include/urdf_utilities/urdf_utilities.h
> +   * \param distance Distance in meter between first and second joint
doxygen: `\return ...` missed

2017-05-04 15:21 UTC, efernandez commented on include/urdf_utilities/urdf_utilities.h
> +   * \param distance Distance in meter between first and second joint
Same below

2017-05-04 15:21 UTC, efernandez commented on include/urdf_utilities/urdf_utilities.h
> +}
`}  // namespace urdf_utilities`

2017-05-04 15:24 UTC, efernandez commented
Re. the naming... maybe `ros_control_urdf_tools` although I think `tools` usually means scripts one can run. Maybe `ros_control_urdf_utils` or `ros_control_urdf_utilities` (I know we should avoid `utils`, but I can't figure out any other name now).

2017-05-05 21:16 UTC, davetcoleman commented
``ros_control_urdf_utils`` +1

2017-05-06 15:20 UTC, vincentrou commented
I think the first remark of @tfoote was to avoid the use of `utils` in the name which does not explain what is doing this pkg. It is why I propose `urdf_kinematics_extractor` instead.

I do not understand the reference to `ros_control` in the name because for me it is not related to it.

2017-05-08 00:00 UTC, davetcoleman commented
Looking at the code just now, seems like ``urdf_geometry_utils`` would be appropriate. or ``urdf_geometry_extractor``, though I like it less.

I think @tfoote's main concern was that it was too generic a name, but adding ``ros_control`` to it certainly narrows its scope

2017-05-08 04:36 UTC, tfoote commented
The postfix_utils doesn't really add information. It basically says that this has useful things in this package. All packages should be generally useful so I'd recommend not even including "utils" as a postfix. As it doesn't add information for introspection/reading clarity.

2017-05-08 15:32 UTC, bmagyar commented
* `ros_control_urdf_parser` -- although it doesn't really parse it 
The problem with `*_kinematics_extractor` is that this package should collect all shared functions of controllers, maybe not only relevant to kinematics. 
How about these?
* `ros_control_urdf_common`
* `ros_controllers_urdf_common`

2017-05-08 16:56 UTC, ipa-mdl commented
:+1: for [`controller_urdf_helpers`](https://github.com/ros-controls/urdf_utilities/pull/1#issuecomment-299139814)

2017-05-08 19:07 UTC, vincentrou commented
@bmagyar For me this package just extract distances and angles from an urdf model. So it can be used by any package that needs those information.
I like the use of `geometry` instead of `kinematics` : 
`urdf_geometry_extractor` or
`urdf_geometry_parser`
If there is not enough proposal !

2017-05-08 21:38 UTC, efernandez commented
I won't add more options ;)
So I'd just :+1: `urdf_geometry_parser` or maybe just `urdf_geometry` (removing the `_utils` suffix).

2017-05-08 21:45 UTC, ipa-mdl commented
`urdf_geometry_parser` works for me :+1:

2017-05-09 10:05 UTC, bmagyar commented
Why `geometry`? I'll pull out the function names here:

```
bool getTransformVector(const std::string& joint_name,
                          const std::string& parent_link_name,
                          urdf::Vector3& transform_vector);
bool getDistanceBetweenJoints(const std::string& first_joint_name,
                                const std::string& second_joint_name,
                                double& distance);
bool getJointRadius(const std::string& joint_name,
                                double& radius);
bool getJointSteeringLimits(const std::string& joint_name,
double& steering_limit);
static bool isCylinder(const boost::shared_ptr<const urdf::Link>& link)
static bool getWheelRadius(const boost::shared_ptr<const urdf::Link>& wheel_link, double& wheel_radius)
``` (let's not discuss function design here just yet)

And I expect similar functions to be added to this package from different controllers later on. 
I still think `ros_controllers_urdf_common` or `ros_controllers_urdf_helpers` or `controllers_urdf_helpers` or `controller_urdf_helpers` would be a better choice.

2017-05-15 08:00 UTC, vincentrou commented
Why not `geometry` ? Those functions are here to get the geometry of the robot (distances, radius, angles).
I do not see the relation with `controllers` since those functions only needs an urdf model and joint name. In fact, for now it will only be used by controllers.

2017-05-15 15:11 UTC, bmagyar commented
Because I think for future extensions a controller-related name gives us more freedom. 
All in all I think we had a general acceptance of `urdf_geometry_parser`, right? I could go with that one too.

Give me a go on it and I'll prepare the repo.

2017-05-18 15:12 UTC, bmagyar commented
Thank you all for taking part in this lengthy debate. I have rename the repo and will be closing this PR now.

@vincentrou the floor is all yours for a new PR ;)

2017-05-18 15:12 UTC, closed without merging