First version of urdf_geometry_parser
ros-controls/urdf_geometry_parser pull request #2
Opened 2017-05-22 15:37 UTC by vincentrou

2017-05-23 10:50 UTC, bmagyar commented
I'll get this in then we talk details ;)

2017-06-16 12:56 UTC, bmagyar requested changes
I'm sorry , forgot to press the green button to submit review :(

2017-06-16 12:56 UTC, bmagyar commented on package.xml
> +  <version>0.2.2</version>
could you change this to 0.0.0 please? this package as is haven't yet been released

2017-06-16 12:56 UTC, bmagyar commented on include/urdf_geometry_parser/urdf_geometry_parser.h
> +  UrdfUtilities(ros::NodeHandle& root_nh, const std::string &base_link);
This class needs a new name.
ParsedRobotModel?
RobotModel? (too general probably)
GeometryParser?

2017-06-16 12:56 UTC, bmagyar commented on src/urdf_geometry_parser.cpp
> +static bool isCylinder(const boost::shared_ptr<const urdf::Link>& link)
These functions should be placed within the `urdf_geometry_parser` namespace.

2017-06-16 13:31 UTC, vincentrou commented
I have made the requested modification.

2017-06-16 13:42 UTC, bmagyar requested changes

2017-06-16 13:42 UTC, bmagyar commented on CMakeLists.txt
> +## The catkin_package macro generates cmake config files for your package
please remove the boilerplate comments from here

2017-06-16 13:42 UTC, bmagyar commented on src/urdf_geometry_parser.cpp
> +  static bool isCylinder(const boost::shared_ptr<const urdf::Link>& link)
I think it is better to remove the static-ness of these 2 non-member functions and add a declaration of them to the header so they are visible.

2017-06-16 13:57 UTC, vincentrou commented on src/urdf_geometry_parser.cpp
> +  static bool isCylinder(const boost::shared_ptr<const urdf::Link>& link)
I don't think it is a good idea to have those functions to be visible.
There are just intend to be used in the getJointRadius function (so not outside of this cpp file).

2017-06-19 09:09 UTC, bmagyar commented on src/urdf_geometry_parser.cpp
> +  static bool isCylinder(const boost::shared_ptr<const urdf::Link>& link)
ideally we'd replace these lines in the `diff_drive_controller` with calls to this library too

https://github.com/ros-controls/ros_controllers/blob/kinetic-devel/diff_drive_controller/src/diff_drive_controller.cpp#L63

https://github.com/ros-controls/ros_controllers/blob/kinetic-devel/diff_drive_controller/src/diff_drive_controller.cpp#L90

https://github.com/ros-controls/ros_controllers/blob/kinetic-devel/diff_drive_controller/src/diff_drive_controller.cpp#L133

2017-06-19 09:36 UTC, vincentrou commented on src/urdf_geometry_parser.cpp
> +  static bool isCylinder(const boost::shared_ptr<const urdf::Link>& link)
Yes this is the purpose of this library.
But the call to [getWheelRadius L546](https://github.com/ros-controls/ros_controllers/blob/kinetic-devel/diff_drive_controller/src/diff_drive_controller.cpp#L546) will be replace by the call to [getJointRadius](https://github.com/vincentrou/urdf_geometry_parser/blob/9fd15e7dffe28c118b567081ba35609289cd02e5/src/urdf_geometry_parser.cpp#L165) in this library (which calls getWheelRadius)

2017-06-21 05:26 UTC, davetcoleman commented on package.xml
> +  <version>0.0.0</version>
needs version number

2017-06-21 07:40 UTC, vincentrou commented on package.xml
> +  <version>0.0.0</version>
It was a request of @bmagyar to reset the version number to 0.0.0 https://github.com/ros-controls/urdf_geometry_parser/pull/2#discussion_r117959144
The version number will be incremented when the package is released right ?

2017-06-21 09:44 UTC, bmagyar approved these changes

2017-06-21 09:44 UTC, bmagyar commented on src/urdf_geometry_parser.cpp
> +  static bool isCylinder(const boost::shared_ptr<const urdf::Link>& link)
Ok, let's leave this pending. I think those functions could be useful outside of this lib, we will see later if making them visible is necessary.

2017-06-21 09:45 UTC, merged

2017-07-02 10:26 UTC, bmagyar commented on package.xml
> +  <version>0.0.0</version>
yep